# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Flask Tutorial for CJU Students
author: Giseop Noh
logo: imgs/prof_noh.jpg
copyright: 'Prof. Giseop Noh in Cheongju University'

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Information about where the book exists on the web
repository: 
  url: https://github.com/kafa46/kafa46.github.io
  path_to_book: tutorial_flask # An optional path to your book, defaults to repo root
  branch: gh-pages  # An optional branch, defaults to `master`
html:
  use_edit_page_button: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
      <p>
          본 책자에 적용되는 라이센스 
          <a href="https://opensource.org/licenses/MIT">
            MIT License
          </a>.
      </p>

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

# 코드 블록에 라인 넘버 추가
markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true